const WIDTH = 100;
const HEIGHT = 40;

// STATES
const DEFAULTSTATE = "";
const STARTSTATE = "start";
const ENDSTATE = "end";
const BARRIERSTATE = "barrier";

// COLORS
const DEFAULTCOLOR = "#fffffe";
const STARTCOLOR = "#17341E"; 
const PATHCOLOR = STARTCOLOR;
const ENDCOLOR = "#5C5A1C";
const BARRIERCOLOR = "#AEA34B";
const QUEUECOLOR = "#f3c6b3";
const VISITEDCOLOR = "#76819c";

export {
    WIDTH,
    HEIGHT,
    DEFAULTCOLOR,
    DEFAULTSTATE,
    STARTSTATE,
    ENDSTATE,
    BARRIERSTATE,
    STARTCOLOR,
    ENDCOLOR,
    BARRIERCOLOR,
    QUEUECOLOR,
    VISITEDCOLOR,
    PATHCOLOR
};